# Generated by Django 5.1.1 on 2024-10-11 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_player_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('health', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RpgStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField(default=1)),
                ('intelligence', models.IntegerField(default=1)),
                ('wisdom', models.IntegerField(default=1)),
                ('dexterity', models.IntegerField(default=1)),
                ('charisma', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='health',
        ),
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
        migrations.AddField(
            model_name='player',
            name='identity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.entities'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(choices=[('head', 'Head'), ('l_hand', 'L Hand'), ('r_hand', 'R Hand'), ('torso', 'Torso'), ('legs', 'Legs'), ('feet', 'Feet')], default=None, max_length=10)),
                ('equipment_material', models.CharField(choices=[('light', 'Light'), ('medium', 'Medium'), ('heavy', 'Heavy')], default=None, max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.entities')),
                ('stat_upgrades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.rpgstats')),
            ],
        ),
        migrations.AddField(
            model_name='entities',
            name='stats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.rpgstats'),
        ),
    ]
