# Generated by Django 5.1.1 on 2024-10-12 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_remove_equipment_owner_entities_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entities',
            name='equipment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.equipment'),
        ),
    ]
