# Generated by Django 5.1.1 on 2024-10-13 20:08

from django.db import migrations

def add_resource_types(apps, schema_editor):
    ResourceTypes = apps.get_model('game', 'ResourceTypes')
    ResourceTypes.objects.create(name='iron')
    ResourceTypes.objects.create(name='wood')
    ResourceTypes.objects.create(name='stone')

def add_action_types(apps, schema_editor):
    ActionTypes = apps.get_model('game', 'Actions')
    ActionTypes.objects.create(action_type='search')
    ActionTypes.objects.create(action_type='explore')    

class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_actions'),
    ]

    operations = [
        migrations.RunPython(add_resource_types),
        migrations.RunPython(add_action_types)
    ]
